// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.subsystems;

import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.PneumaticsModuleType;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

import static frc.robot.Constants.*;

public class Compression extends SubsystemBase {
    private boolean running;
    public Compressor mainCompressor;

    public Compression() {
        mainCompressor = new Compressor(kCompressorModuleId, PneumaticsModuleType.CTREPCM);
        mainCompressor.disable();
        running = false;
        printStatus();
    }

    // @Override
    // public void initDefaultCommand() {
    //     setDefaultCommand(new RunCompressor());
    // }

//     @Override
//     public void periodic() {
//        printStatus();
//     }

    // public boolean isActiveAndCharged() {
    //     return (running && mainCompressor.getPressureSwitchValue());
    // }

    public void startCompressor() {
        running = true;
        mainCompressor.enableDigital();
        printStatus();
    }

    public void stopCompressor(){
        running = false;
        mainCompressor.disable();
        printStatus();
    }

    private void printStatus() {
        System.out.println("\n\nShould be running: " + running);
        System.out.println("Compressor isEnabled: " + mainCompressor.isEnabled());
        System.out.println("Compressor getPressureSwitchValve: " + mainCompressor.getPressureSwitchValue());
    }
}
